backend/myproject/core/urls.py
from django.urls import path
from myproject.core import views as v

app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'),
    path('dashboard/', v.dashboard, name='dashboard'),
    path('configs/', v.configs, name='configs'),
    path('configs/edit/', v.configs_edit, name='configs_edit'),
]

backend/myproject/financial/urls.py
from django.urls import include, path
from myproject.financial import views as f

app_name = 'financial'

financial_patterns = [
    path('', f.Financial.as_view(), name='financial'),
    path('receipts/', f.receipts, name='receipts'),
    path('paying_source/', f.paying_source, name='paying_source'),
    path('type_expense/', f.type_expense, name='type_expense'),
    path('cost_center/', f.cost_center, name='cost_center'),
]

urlpatterns = [
    path('financial/', include(financial_patterns)),
]

backend/myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('myproject.core.urls')),
    path('accounts/', include('myproject.accounts.urls')),
    path('api/crm/', include('myproject.crm.urls')),
    # path('crm/', include('myproject.crm.urls')),
    path('financial/', include('myproject.financial.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

backend/myproject/core/models.py
from django.db import models
from localflavor.br.br_states import STATE_CHOICES


class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em',
        auto_now_add=True,
        auto_now=False
    )
    modified = models.DateTimeField(
        'modificado em',
        auto_now_add=False,
        auto_now=True
    )

    class Meta:
        abstract = True


class Address(models.Model):
    address = models.CharField(
        'endereço',
        max_length=100,
        null=True,
        blank=True
    )
    address_number = models.IntegerField('número', null=True, blank=True)
    complement = models.CharField(
        'complemento',
        max_length=100,
        null=True,
        blank=True
    )
    district = models.CharField('bairro', max_length=100, blank=True)
    city = models.CharField('cidade', max_length=100, blank=True)
    uf = models.CharField(
        'UF',
        max_length=2,
        choices=STATE_CHOICES,
        null=True,
        blank=True
    )
    cep = models.CharField('CEP', max_length=9, null=True, blank=True)

    class Meta:
        abstract = True


class Document(models.Model):
    cpf = models.CharField(
        'CPF',
        max_length=14,
        unique=True,
        null=True,
        blank=True
    )
    rg = models.CharField('RG', max_length=11, null=True, blank=True)
    cnh = models.CharField('CNH', max_length=20, null=True, blank=True)
    cnpj = models.CharField(
        'CNPJ',
        max_length=18,
        unique=True,
        null=True,
        blank=True
    )
    imun = models.CharField(
        'Inscrição Municipal',
        max_length=12,
        null=True,
        blank=True
    )
    ie = models.CharField(
        'Inscrição Estadual',
        max_length=12,
        null=True,
        blank=True
    )

    class Meta:
        abstract = True


class Active(models.Model):
    active = models.BooleanField('ativo', default=True)

    class Meta:
        abstract = True

backend/myproject/core/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


def index(request):
    ctx = {'mydebug': True}
    return render(request, 'index.html', ctx)


def dashboard(request):
    return render(request, 'dashboard.html')


@login_required
def configs(request):
    return render(request, 'configs.html')


@login_required
def configs_edit(request):
    return render(request, 'configs_edit.html')

backend/myproject/core/templates/includes/aside-menu.html
{% load static %}
<aside class="aside-menu">
  <ul class="nav nav-tabs" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" href="#timeline" role="tab">
        <i class="icon-list"></i>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#messages" role="tab">
        <i class="icon-speech"></i>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#settings" role="tab"> <i class="icon-settings"></i>
      </a>
    </li>
  </ul>
  <!-- Tab panes-->
  <div class="tab-content">
    <div class="tab-pane active" id="timeline" role="tabpanel">
      <div class="list-group list-group-accent">
        <div class="list-group-item list-group-item-accent-secondary bg-light text-center font-weight-bold text-muted text-uppercase small">Today</div>
        <div class="list-group-item list-group-item-accent-warning list-group-item-divider">
          <div class="avatar float-right">
            <img class="img-avatar" src="{% static 'img/avatars/7.jpg' %}" alt="admin@bootstrapmaster.com">
          </div>
          <div>Meeting with
            <strong>Lucas</strong>
          </div>
          <small class="text-muted mr-3">
          <i class="icon-calendar"></i>  1 - 3pm</small>
          <small class="text-muted">
          <i class="icon-location-pin"></i>  Palo Alto, CA</small>
        </div>
        <div class="list-group-item list-group-item-accent-info">
          <div class="avatar float-right">
            <img class="img-avatar" src="{% static 'img/avatars/4.jpg' %}" alt="admin@bootstrapmaster.com">
          </div>
          <div>Skype with
            <strong>Megan</strong>
          </div>
          <small class="text-muted mr-3">
          <i class="icon-calendar"></i>  4 - 5pm</small>
          <small class="text-muted">
          <i class="icon-social-skype"></i>  On-line</small>
        </div>
        <div class="list-group-item list-group-item-accent-secondary bg-light text-center font-weight-bold text-muted text-uppercase small">Tomorrow</div>
        <div class="list-group-item list-group-item-accent-danger list-group-item-divider">
          <div>New UI Project -
            <strong>deadline</strong>
          </div>
          <small class="text-muted mr-3">
          <i class="icon-calendar"></i>  10 - 11pm</small>
          <small class="text-muted">
          <i class="icon-home"></i>  creativeLabs HQ</small>
          <div class="avatars-stack mt-2">
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="{% static 'img/avatars/2.jpg' %}" alt="admin@bootstrapmaster.com">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="{% static 'img/avatars/3.jpg' %}" alt="admin@bootstrapmaster.com">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="{% static 'img/avatars/4.jpg' %}" alt="admin@bootstrapmaster.com">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="{% static 'img/avatars/5.jpg' %}" alt="admin@bootstrapmaster.com">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="{% static 'img/avatars/6.jpg' %}" alt="admin@bootstrapmaster.com">
            </div>
          </div>
        </div>
        <div class="list-group-item list-group-item-accent-success list-group-item-divider">
          <div>
          <strong>#10 Startups.Garden</strong> Meetup</div>
          <small class="text-muted mr-3">
          <i class="icon-calendar"></i>  1 - 3pm</small>
          <small class="text-muted">
          <i class="icon-location-pin"></i>  Palo Alto, CA</small>
        </div>
        <div class="list-group-item list-group-item-accent-primary list-group-item-divider">
          <div>
            <strong>Team meeting</strong>
          </div>
          <small class="text-muted mr-3">
          <i class="icon-calendar"></i>  4 - 6pm</small>
          <small class="text-muted">
          <i class="icon-home"></i>  creativeLabs HQ</small>
          <div class="avatars-stack mt-2">
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="{% static 'img/avatars/2.jpg' %}" alt="admin@bootstrapmaster.com">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="{% static 'img/avatars/3.jpg' %}" alt="admin@bootstrapmaster.com">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="{% static 'img/avatars/4.jpg' %}" alt="admin@bootstrapmaster.com">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="{% static 'img/avatars/5.jpg' %}" alt="admin@bootstrapmaster.com">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="{% static 'img/avatars/6.jpg' %}" alt="admin@bootstrapmaster.com">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="{% static 'img/avatars/7.jpg' %}" alt="admin@bootstrapmaster.com">
            </div>
            <div class="avatar avatar-xs">
              <img class="img-avatar" src="{% static 'img/avatars/8.jpg' %}" alt="admin@bootstrapmaster.com">
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="tab-pane p-3" id="messages" role="tabpanel">
      <div class="message">
        <div class="py-3 pb-5 mr-3 float-left">
          <div class="avatar">
            <img class="img-avatar" src="{% static 'img/avatars/7.jpg' %}" alt="admin@bootstrapmaster.com">
            <span class="avatar-status badge-success"></span>
          </div>
        </div>
        <div>
          <small class="text-muted">Lukasz Holeczek</small>
          <small class="text-muted float-right mt-1">1:52 PM</small>
        </div>
        <div class="text-truncate font-weight-bold">Lorem ipsum dolor sit amet</div>
        <small class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</small>
      </div>
      <hr>
      <div class="message">
        <div class="py-3 pb-5 mr-3 float-left">
          <div class="avatar">
            <img class="img-avatar" src="{% static 'img/avatars/7.jpg' %}" alt="admin@bootstrapmaster.com">
            <span class="avatar-status badge-success"></span>
          </div>
        </div>
        <div>
          <small class="text-muted">Lukasz Holeczek</small>
          <small class="text-muted float-right mt-1">1:52 PM</small>
        </div>
        <div class="text-truncate font-weight-bold">Lorem ipsum dolor sit amet</div>
        <small class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</small>
      </div>
      <hr>
      <div class="message">
        <div class="py-3 pb-5 mr-3 float-left">
          <div class="avatar">
            <img class="img-avatar" src="{% static 'img/avatars/7.jpg' %}" alt="admin@bootstrapmaster.com">
            <span class="avatar-status badge-success"></span>
          </div>
        </div>
        <div>
          <small class="text-muted">Lukasz Holeczek</small>
          <small class="text-muted float-right mt-1">1:52 PM</small>
        </div>
        <div class="text-truncate font-weight-bold">Lorem ipsum dolor sit amet</div>
        <small class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</small>
      </div>
      <hr>
      <div class="message">
        <div class="py-3 pb-5 mr-3 float-left">
          <div class="avatar">
            <img class="img-avatar" src="{% static 'img/avatars/7.jpg' %}" alt="admin@bootstrapmaster.com">
            <span class="avatar-status badge-success"></span>
          </div>
        </div>
        <div>
          <small class="text-muted">Lukasz Holeczek</small>
          <small class="text-muted float-right mt-1">1:52 PM</small>
        </div>
        <div class="text-truncate font-weight-bold">Lorem ipsum dolor sit amet</div>
        <small class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</small>
      </div>
      <hr>
      <div class="message">
        <div class="py-3 pb-5 mr-3 float-left">
          <div class="avatar">
            <img class="img-avatar" src="{% static 'img/avatars/7.jpg' %}" alt="admin@bootstrapmaster.com">
            <span class="avatar-status badge-success"></span>
          </div>
        </div>
        <div>
          <small class="text-muted">Lukasz Holeczek</small>
          <small class="text-muted float-right mt-1">1:52 PM</small>
        </div>
        <div class="text-truncate font-weight-bold">Lorem ipsum dolor sit amet</div>
        <small class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</small>
      </div>
    </div>
    <div class="tab-pane p-3" id="settings" role="tabpanel">
      <h6>Settings</h6>
      <div class="aside-options">
        <div class="clearfix mt-4">
          <small>
          <b>Option 1</b>
          </small>
          <label class="switch switch-text switch-pill switch-success switch-sm float-right">
            <input class="switch-input" type="checkbox" checked="">
            <span class="switch-label" data-on="On" data-off="Off"></span>
            <span class="switch-handle"></span>
          </label>
        </div>
        <div>
          <small class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</small>
        </div>
      </div>
      <div class="aside-options">
        <div class="clearfix mt-3">
          <small>
          <b>Option 2</b>
          </small>
          <label class="switch switch-text switch-pill switch-success switch-sm float-right">
            <input class="switch-input" type="checkbox">
            <span class="switch-label" data-on="On" data-off="Off"></span>
            <span class="switch-handle"></span>
          </label>
        </div>
        <div>
          <small class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</small>
        </div>
      </div>
      <div class="aside-options">
        <div class="clearfix mt-3">
          <small>
          <b>Option 3</b>
          </small>
          <label class="switch switch-text switch-pill switch-success switch-sm float-right">
            <input class="switch-input" type="checkbox">
            <span class="switch-label" data-on="On" data-off="Off"></span>
            <span class="switch-handle"></span>
          </label>
        </div>
      </div>
      <div class="aside-options">
        <div class="clearfix mt-3">
          <small>
          <b>Option 4</b>
          </small>
          <label class="switch switch-text switch-pill switch-success switch-sm float-right">
            <input class="switch-input" type="checkbox" checked="">
            <span class="switch-label" data-on="On" data-off="Off"></span>
            <span class="switch-handle"></span>
          </label>
        </div>
      </div>
      <hr>
      <h6>System Utilization</h6>
      <div class="text-uppercase mb-1 mt-4">
        <small>
        <b>CPU Usage</b>
        </small>
      </div>
      <div class="progress progress-xs">
        <div class="progress-bar bg-info" role="progressbar" style="width: 25%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
      <small class="text-muted">348 Processes. 1/4 Cores.</small>
      <div class="text-uppercase mb-1 mt-2">
        <small>
        <b>Memory Usage</b>
        </small>
      </div>
      <div class="progress progress-xs">
        <div class="progress-bar bg-warning" role="progressbar" style="width: 70%;" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
      <small class="text-muted">11444GB/16384MB</small>
      <div class="text-uppercase mb-1 mt-2">
        <small>
        <b>SSD 1 Usage</b>
        </small>
      </div>
      <div class="progress progress-xs">
        <div class="progress-bar bg-danger" role="progressbar" style="width: 95%;" aria-valuenow="95" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
      <small class="text-muted">243GB/256GB</small>
      <div class="text-uppercase mb-1 mt-2">
        <small>
        <b>SSD 2 Usage</b>
        </small>
      </div>
      <div class="progress progress-xs">
        <div class="progress-bar bg-success" role="progressbar" style="width: 10%;" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
      <small class="text-muted">25GB/256GB</small>
    </div>
  </div>
</aside>

backend/myproject/core/templates/includes/breadcrumb.html
{% block breadcrumb %}

<li class="breadcrumb-item active">{{ model_name_plural }}</li>

{% endblock %}

backend/myproject/core/templates/includes/breadcrumb_add.html
{% block breadcrumb %}
<li class="breadcrumb-item"><a href="/crm/{{ modelname.lower }}/">{{ model_name_plural }}</a></li>
<li class="breadcrumb-item active">Adicionar</li>

{% endblock %}

backend/myproject/core/templates/includes/breadcrumb_detail.html
{% block breadcrumb %}

<li class="breadcrumb-item"><a href="{{ object.list_url }}">{{ model_name_plural }}</a></li>
<li class="breadcrumb-item">{{ object }}</li>
<li class="breadcrumb-item active">Detalhes</li>

{% endblock %}

backend/myproject/core/templates/includes/breadcrumb_update.html
{% block breadcrumb %}

<li class="breadcrumb-item"><a href="{{ object.list_url }}">{{ model_name_plural }}</a></li>
<li class="breadcrumb-item"><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>
<li class="breadcrumb-item active">Editar</li>

{% endblock %}

backend/myproject/core/templates/includes/footer.html
<footer class="app-footer">
  <div>
    <a href="">CRM</a>
    <span>&copy; 2018</span>
  </div>
  <!-- <div class="ml-auto">
    <span>Powered by</span>
    <a href="">CoreUI</a>
  </div> -->
</footer>

backend/myproject/core/templates/includes/nav.html
{% load static %}
<header class="app-header navbar">
  <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
  <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="{% url 'core:index' %}">
    <img src="{% static 'img/brand/sygnet.svg' %}" alt="logo" width="30px">
  </a>
  <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button" data-toggle="sidebar-lg-show">
  <span class="navbar-toggler-icon"></span>
  </button>
  <ul class="nav navbar-nav ml-auto">
    {% if user.is_authenticated %}
      <li class="nav-item d-md-down-none">
        <span class="nav-link">
          Olá {{ request.user.first_name }}
        </span>
      </li>
    {% endif %}
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="" role="button" aria-haspopup="true" aria-expanded="false">
        <img class="img-avatar" src="{% static 'img/avatars/7.jpg' %}" alt="admin@bootstrapmaster.com">
      </a>
      <div class="dropdown-menu dropdown-menu-right">
        <div class="dropdown-header text-center">
          <strong>Configurações</strong>
        </div>
        <a class="dropdown-item" href=".">
        <i class="fa fa-lock"></i> Logout</a>
      </div>
    </li>
  </ul>
  <button class="navbar-toggler aside-menu-toggler d-md-down-none" type="button" data-toggle="aside-menu-lg-show">
  <span class="navbar-toggler-icon"></span>
  </button>
  <button class="navbar-toggler aside-menu-toggler d-lg-none" type="button" data-toggle="aside-menu-show">
  <span class="navbar-toggler-icon"></span>
  </button>
</header>

backend/myproject/core/templates/includes/sidebar.html
{% load static %}
<div class="sidebar">
  <nav class="sidebar-nav">
    <ul class="nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:dashboard' %}">
          <i class="nav-icon icon-speedometer"></i> Dashboard
          <!-- <span class="badge badge-primary">NEW</span> -->
        </a>
      </li>
      <li class="nav-title">CRM</li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'crm:employee_list' %}">
        <i class="nav-icon icon-user"></i> Usuários</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'crm:company_list' %}">
        <i class="nav-icon icon-people"></i> Clientes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'crm:provider_list' %}">
        <i class="nav-icon icon-cursor"></i> Fornecedores</a>
      </li>
      <!-- <li class="nav-title">Proposta</li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <i class="nav-icon icon-book-open"></i> Proposta
          <span class="badge badge-primary">7</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <i class="nav-icon icon-clock"></i> Horários
          <span class="badge badge-warning">10</span>
        </a>
      </li> -->
      <li class="nav-title">Financeiro</li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'financial:financial' %}">
        <i class="nav-icon icon-wallet"></i> Financeiro</a>
      </li>
      <!-- <li class="nav-item nav-dropdown">
        <a class="nav-link nav-dropdown-toggle" href="">
        <i class="nav-icon icon-star"></i> Icons</a>
        <ul class="nav-dropdown-items">
          <li class="nav-item">
            <a class="nav-link" href="icons-flags.html">
              <i class="nav-icon icon-star"></i> Flags
              <span class="badge badge-success">NEW</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="icons-font-awesome.html">
              <i class="nav-icon icon-star"></i> Font Awesome
              <span class="badge badge-secondary">4.7</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="icons-simple-line-icons.html">
            <i class="nav-icon icon-star"></i> Simple Line Icons</a>
          </li>
        </ul>
      </li> -->
      <!-- <li class="divider"></li>
      <li class="nav-title">Extras</li>
      <li class="nav-item nav-dropdown">
        <a class="nav-link nav-dropdown-toggle" href="">
        <i class="nav-icon icon-star"></i> Pages</a>
        <ul class="nav-dropdown-items">
          <li class="nav-item">
            <a class="nav-link" href="login.html" target="_top">
            <i class="nav-icon icon-star"></i> Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="register.html" target="_top">
            <i class="nav-icon icon-star"></i> Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="404.html" target="_top">
            <i class="nav-icon icon-star"></i> Error 404</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="500.html" target="_top">
            <i class="nav-icon icon-star"></i> Error 500</a>
          </li>
        </ul>
      </li>
      <li class="nav-item mt-auto">
        <a class="nav-link nav-link-success" href="https://coreui.io" target="_top">
        <i class="nav-icon icon-cloud-download"></i> Download CoreUI</a>
      </li>
      <li class="nav-item">
        <a class="nav-link nav-link-danger" href="https://coreui.io/pro/" target="_top">
          <i class="nav-icon icon-layers"></i> Try CoreUI
          <strong>PRO</strong>
        </a>
      </li> -->
    </ul>
  </nav>
  <button id="foot_btn" class="sidebar-minimizer brand-minimizer" type="button"></button>
</div>